name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build-mac:
    name: build-mac
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'recursive'

      - name: Cache Dependencies
        uses: actions/cache@main
        with:
          path: /Users/runner/Library/Caches/Homebrew
          key: ${{ runner.os }}-deps-cache

      - name: Install Dependencies
        run: |
          brew cleanup
          brew install qt@5

      - name: Build
        run: |
          mkdir build
          cd build
          cmake \
           -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
           -DCMAKE_C_COMPILER=/usr/bin/clang \
           -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
           -DCMAKE_BUILD_TYPE=Release \
           -DLauncher_NOTIFICATION_URL:STRING=https://files.multimc.org/notifications.json \
           -DCMAKE_INSTALL_PREFIX:PATH="/Users/runner/work/UltimMC/build/dist" \
           -DCMAKE_PREFIX_PATH="$(brew --prefix qt@5)/lib/cmake" \
           -DQt5_DIR="$(brew --prefix qt@5)" \
           -DLauncher_UPDATER_BASE=https://files.multimc.org/update/ \
           -DLauncher_PASTE_EE_API_KEY:STRING=utLvciUouSURFzfjPxLBf5W4ISsUX4pwBDF7N1AfZ \
           -DLauncher_ANALYTICS_ID:STRING=UA-87731965-2 \
           -DLauncher_LAYOUT=mac-bundle \
           -DLauncher_BUILD_PLATFORM=osx64-5.15.2 \
           -DLauncher_BUG_TRACKER_URL=https://github.com/UltimMC/Launcher/issues \
           -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 \
           -DLauncher_EMBED_SECRETS=On \
           $GITHUB_WORKSPACE

      - name: Compile
        run: |
          cd build
          make -j$(sysctl -n hw.logicalcpu)

      - name: Test
        run: |
          cd build
          make test
          cmake -E remove_directory "/Users/runner/work/UltimMC/build/dist"

      - name: Install
        run: |
          cd build
          make install
          chmod +x /Users/runner/work/UltimMC/build/dist/UltimMC.app/Contents/MacOS/UltimMC

      - name: Upload Artifacts
        uses: actions/upload-artifact@main
        with:
          name: mmc-cracked-osx64
          path: /Users/runner/work/UltimMC/build/dist
